### ISSUE TITLE
Problem with EGA install

### ISSUE THREAD

**Issue by atomashevic** [hfgolino/EGA#16]
Hello,

I have an issue with EGA package installation.

`library(devtools)`
`install_github("hfgolino/EGA", dep = TRUE)`

Gives following error:

`Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/hfgolino/EGA/tarball/master'`

I assume package will be avaliable on CRAN very soon, but currently I can't see no other way of installing it. Thanks!

Aleksandar

**Comment by hfgolino** [comment]
Hi Aleksandar, thanks for your message. Could you, please, let me know when you tried to install the package, as well as your R version? Cheers, Hudson

**Comment by atomashevic** [comment]
`R version 3.5.2 (2018-12-20)`
Running on x64 Windows 7.

I've tried installing earlier today and seconds before this comment. Had no issues installing on another PC few months ago (R 3.5.1).

**Comment by atomashevic** [comment]
I've solved it, it was an issue on my end with devtools and my Internet connection. I didn't had TLS 1.2 support enabled. I'm sory if I wasted your time. Thanks for the answer and thanks for your amazing work!

**Comment by hfgolino** [comment]
Ok. Good to know that it's working for you now! Let me know if you have any
other questions.

best,

Hudson



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em dom, 17 de fev de 2019 às 18:09, atomashevic <notifications@github.com>
escreveu:

**Comment by atomashevic** [comment]
Hi,

Here's a bug I accidentally found out.

There's a caps issue in CFA function with WLS estimator. In your functions the default test statistic is set as `"satorra-bentler".` When I try to use it, I get a following error:

`Error in lav_options_set(opt) : 
  lavaan ERROR: invalid value for test argument when estimator is WLS: satorra.bentler`

According to lavaan package test argument should take value `"Satorra-Bentler"`

Cheers,
Aleksandar

**Comment by hfgolino** [comment]
What type of data do you have?

If its dichotomous or categorical ordinal, you can use the WLSMV estimation.

Cheers,



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qua, 20 de fev de 2019 às 11:11, atomashevic <notifications@github.com>
escreveu:
